name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # 2. Install Hugging Face Hub
      - name: Install Hugging Face Hub
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade huggingface_hub

      # 3. Push repo contents to Hugging Face Space
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        shell: python
        run: |
          from huggingface_hub import HfApi
          import os

          api = HfApi()
          token = os.environ["HF_TOKEN"]

          # 🔴 CHANGE THIS IF YOUR SPACE NAME IS DIFFERENT
          repo_id = "Arko007/heart-disease"

          print(f"🚀 Syncing repository to HF Space: {repo_id}")

          api.upload_folder(
              folder_path=".",
              repo_id=repo_id,
              repo_type="space",
              token=token,
              ignore_patterns=[
                  ".git/*",
                  ".github/*",
                  ".venv/*",
                  "node_modules/*",
                  "__pycache__/*",
                  "*.log"
              ],
          )

          print("✅ Upload complete! Hugging Face Space will now rebuild.")

